const quranText = [
    {
        ayat:'اَلْهٰىكُمُ التَّكَاثُرُ',
        soorahArabic: 'سُوْرَۃُ التَّكَاثُر',
        soorahEnglish: 'Sura Takasur',
        soorahNo: 102,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 1,
       page:1,
    },
    {
        ayat:'حَتّٰى زُرْتُمُ الْمَقَابِرَ',
        soorahArabic: 'سُوْرَۃُ التَّكَاثُر',
        soorahEnglish: 'Sura Takasur',
        soorahNo: 102,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 2,
       page:1,
    },
    {
        ayat:' كَلَّا سَوْفَ تَعْلَمُوْنَ',
        soorahArabic: 'سُوْرَۃُ التَّكَاثُر',
        soorahEnglish: 'Sura Takasur',
        soorahNo: 102,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 3,
       page:1,
    },
    {
        ayat:'  ثُمَّ كَلَّا سَوْفَ تَعْلَمُوْنَ',
        soorahArabic: 'سُوْرَۃُ التَّكَاثُر',
        soorahEnglish: 'Sura Takasur',
        soorahNo: 102,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 4,
       page:1,
    },
    {
        ayat:' كَلَّا لَوْ تَعْلَمُوْنَ عِلْمَ الْیَقِیْنِ',
        soorahArabic: 'سُوْرَۃُ التَّكَاثُر',
        soorahEnglish: 'Sura Takasur',
        soorahNo: 102,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 5,
       page:1,
    },
    {
        ayat:' لَتَرَوُنَّ الْجَحِیْمَ',
        soorahArabic: 'سُوْرَۃُ التَّكَاثُر',
        soorahEnglish: 'Sura Takasur',
        soorahNo: 102,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 6,
       page:1,
    },
    {
        ayat:'ثُمَّ لَتَرَوُنَّهَا عَیْنَ الْیَقِیْنِ',
        soorahArabic: 'سُوْرَۃُ التَّكَاثُر',
        soorahEnglish: 'Sura Takasur',
        soorahNo: 102,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 7,
       page:1,
    },
    {
        ayat:' ثُمَّ لَتُسْــٴَـلُنَّ یَوْمَىٕذٍ عَنِ النَّعِیْمِ',
        soorahArabic: 'سُوْرَۃُ التَّكَاثُر',
        soorahEnglish: 'Sura Takasur',
        soorahNo: 102,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 7,
       page:1,
    },

]

