const quranText = [
    {
        ayat:'وَ الْعَصْرِ',
        soorahArabic: 'سُوْرَۃُ العَصْر',
        soorahEnglish: 'Sura Asr',
        soorahNo: 103,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 1,
       page:1,
    },
    {
        ayat:'اِنَّ الْاِنْسَانَ لَفِیْ خُسْرٍ',
        soorahArabic: 'سُوْرَۃُ العَصْر',
        soorahEnglish: 'Sura Asr',
        soorahNo: 103,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 2,
       page:1,
    },
    {
        ayat:' اِلَّا الَّذِیْنَ اٰمَنُوْا وَ عَمِلُوا الصّٰلِحٰتِ وَ تَوَاصَوْا بِالْحَقِّ ﳔ وَ تَوَاصَوْا بِالصَّبْرِ',
        soorahArabic: 'سُوْرَۃُ العَصْر',
        soorahEnglish: 'Sura Asr',
        soorahNo: 103,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 3,
       page:1,
    },
]
