const quranText = [
    {
        ayat: 'لِاِیْلٰفِ قُرَیْشٍ',
        soorahArabic: 'سُوْرَۃ قُرَيْش',
        soorahEnglish: 'Sura Quraish',
        soorahNo: 106,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 1,
       page:1,
    },
    {
        ayat: 'لٰفِهِمْ رِحْلَةَ الشِّتَآءِ وَ الصَّیْفِ',
        soorahArabic: 'سُوْرَۃ قُرَيْش',
        soorahEnglish: 'Sura Quraish',
        soorahNo: 106,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 2,
       page:1,
    },
    {
        ayat: ' فَلْیَعْبُدُوْا رَبَّ هٰذَا الْبَیْتِ',
        soorahArabic: 'سُوْرَۃ قُرَيْش',
        soorahEnglish: 'Sura Quraish',
        soorahNo: 106,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 3,
       page:1,
    },
    {
        ayat: 'الَّذِیْۤ اَطْعَمَهُمْ مِّنْ جُوْ عٍ ﳔ وَّ اٰمَنَهُمْ مِّنْ خَوْفٍ',
        soorahArabic: 'سُوْرَۃ قُرَيْش',
        soorahEnglish: 'Sura Quraish',
        soorahNo: 106,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 4,
       page:1,
    },
]