const quranText = [
    {
        ayat: 'اَرَءَیْتَ الَّذِیْ یُكَذِّبُ بِالدِّیْنِ',
        soorahArabic: '	سُوْرَۃُ المَاعُون',
        soorahEnglish: 'Sura Maoon',
        soorahNo: 107,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 1,
       page:1,
    },
    {
        ayat: 'فَذٰلِكَ الَّذِیْ یَدُعُّ الْیَتِیْمَ',
        soorahArabic: '	سُوْرَۃُ المَاعُون',
        soorahEnglish: 'Sura Maoon',
        soorahNo: 107,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 2,
       page:1,
    },
    {
        ayat: 'وَ لَا یَحُضُّ عَلٰى طَعَامِ الْمِسْكِیْنِ',
        soorahArabic: '	سُوْرَۃُ المَاعُون',
        soorahEnglish: 'Sura Maoon',
        soorahNo: 107,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 3,
       page:1,
    },
    {
        ayat: 'فَوَیْلٌ لِّلْمُصَلِّیْنَ',
        soorahArabic: '	سُوْرَۃُ المَاعُون',
        soorahEnglish: 'Sura Maoon',
        soorahNo: 107,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 4,
       page:1,
    },
    {
        ayat: 'الَّذِیْنَ هُمْ عَنْ صَلَاتِهِمْ سَاهُوْنَ',
        soorahArabic: '	سُوْرَۃُ المَاعُون',
        soorahEnglish: 'Sura Maoon',
        soorahNo: 107,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 5,
       page:1,
    },
    {
        ayat: ' الَّذِیْنَ هُمْ یُرَآءُوْنَ',
        soorahArabic: '	سُوْرَۃُ المَاعُون',
        soorahEnglish: 'Sura Maoon',
        soorahNo: 107,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 6,
       page:1,
    },
    {
        ayat: ' وَ یَمْنَعُوْنَ الْمَاعُوْنَ',
        soorahArabic: '	سُوْرَۃُ المَاعُون',
        soorahEnglish: 'Sura Maoon',
        soorahNo: 107,
        siparaNo: 30,
        rukuNo: 1,
        ayatNo: 7,
       page:1,
    },
]